import './__button/__button.css';
import './__button/__button.js';
import './__button/_button_color-aqua/_button_color-aqua.css';
import './__button/_button_size-big/_button_size-big.css';
import './__button/_button_color-red/_button_color-red.css';
import './__arrow-button/_arrow-button_left.css';
import './__arrow-button/_arrow-button_right.css';
import './__arrow-button/_arrow-button_left-disabled.css';
import './__arrow-button/_arrow-button_right-disabled.css';
import './__percentage/_percentage.css';
import './__percentage/_percentage.js';
import './__pie-chart/_pie-chart.css';
import './__pie-chart/_pie-chart.js';
import './__slider-orange/_slider-orange.css';
import './__slider-orange/_slider-orange.js';
import './__slider-aqua/_slider-aqua.css';
import './__slider-aqua/_slider-aqua.js';
import './__progressbar/_progressbar.css';
import './__form/_text.css';
import './__form/_text.js';
import './__form/_validation-cloud.css';
import './__form/_email.css';
import './__form/_email.js';
import './__form/_form-elements.css';
import './__form/_submit-button.css';
import './__form/_textarea.css';
import './__form/_toggle.css';
import './__form/_tick-boxes.css';
import './__form/_search-box/_search-box.css';
import './__form/_search-box/_search-box.js';
import './__form/_select.css';
import './__user-profile/_developer-box/_developer-box.css';
import './__news/_news.css';
import './__events/_events.css';
import './__map/_map.css';
import './__map/_map.js';
import './__calendar/_calendar.css';
import './__calendar/_calendar.js';
import './__message-window/_message-window.css';
import './__fonts/Lato-Black/Lato-Black.css';
import './__button/button-position.css';
import './__arrow-button/arrow-button-position.css';
import './__percentage/percentage-position.css';
import './__slider-aqua/slider-position.css';
import './__progressbar/progressbar-position.css'
import './__message-window/_message-window-photo.js';
import './__user-profile/_developer-box/_developer-photo.js';
import './__user-profile/_developer-box/_developer-box-position.css';
import './__news/news-events-position.css';
import './__map/map-position.css';
import './__calendar/calendar-messaging-position.css';
import './__video/video-position.css';
import './__body/body.css';
require('./__map/_map_images/Pin.png');
require('./__map/_map_images/MyLocation.png');
require('./__map/_map_images/map-marker.png');
require('./__events/_news-images/event-image1.png');
require('./__fonts/Lato-Black/Lato-Black.eot');
require('./__fonts/Lato-Black/Lato-Black.svg');
require('./__fonts/Lato-Black/Lato-Black.ttf');
require('./__fonts/Lato-Black/Lato-Black.woff');
require('./__message-window/_message-window-icon/CameraIcon.png');
require('./__message-window/_message-window-icon/ChatIcon.png');
require('./__message-window/_message-window-photo/developer-photo1.png');
require('./__message-window/_message-window-photo/developer-photo2.png');
require('./__news/_news-images/news-photo1.png');
require('./__user-profile/_developer-photo/developer-photo1.png');
require('./__user-profile/_developer-photo/developer-photo2.png');